baseURL = "https://muxin.io/"
title = "My New Hugo Site"
theme = "hugo-PaperMod"
defaultContentLanguage = "cn"

[params]
    [[params.socialIcons]]
        name = "Github"
        url = "https://github.com/mxseraph"
    [[params.socialIcons]]
        name = "Telegram"
        url = "/archive"

[languages]
    [languages.cn]
        languageName = "中文"
        title = "方牧心的个人网站"
        [languages.cn.params.profileMode]
            enabled = true
            title = "你好"
    [languages.en]
        languageName = "English"
        title = "Muxin Fang's Website"
        [languages.en.params.profileMode]
            enabled = true
            title = "Hello"
