baseURL = "https://muxin.io/"
theme = "hugo-PaperMod"
defaultContentLanguage = "zh"

googleAnalytics = "G-6T32Y0LV39"

[minify]
    disableXML = true
    minifyOutput = true

[params]
    env = "production"
    defaultTheme = "auto"
    disableThemeToggle = false
    disableSpecial1stPost = false
    ShowReadingTime = true
    [[params.socialIcons]]
        name = "Github"
        url = "https://github.com/mxseraph"
    [[params.socialIcons]]
        name = "Telegram"
        url = "https://t.me/MxSeraph"

[languages]
    [languages.zh]
        languageName = "Chinese"
        title = "方牧心的网站"
        [languages.zh.params]
            description = "这都被你给发现了"
            author = "方牧心"
        [languages.zh.params.label]
            text = "轻语慕心"
            icon = "/apple-touch-icon.png"
            iconHeight = 35
        [languages.zh.params.profileMode]
            enabled = true
            title = "方牧心"
            imageUrl = "/avatar.png"
        [[languages.zh.params.profileMode.buttons]]
            name = "博客"
            url = "https://blog.muxin.io"
        [[languages.zh.menu.main]]
            identifier = "home"
            name = "首页"
            url = "/"
            weight = -2
        [[languages.zh.menu.main]]
            identifier = "blog"
            name = "博客"
            url = "https://blog.muxin.io"
            weight = -1
        [[languages.zh.menu.main]]
            identifier = "about"
            name = "关于我"
            url = "/about/"
    [languages.en]
        languageName = "English"
        title = "Muxin Fang's Website"
        [languages.en.params]
            description = "You found something"
            author = "Muxin Fang"
        [languages.en.params.label]
            text = "Whisper from Heart"
            icon = "/apple-touch-icon.png"
            iconHeight = 35
        [languages.en.params.profileMode]
            enabled = true
            title = "Muxin Fang"
            imageUrl = "/avatar.png"
        [[languages.en.params.profileMode.buttons]]
            name = "Blog"
            url = "https://blog.muxin.io/en"
        [[languages.en.menu.main]]
            identifier = "home"
            name = "Home"
            url = "/"
            weight = -2
        [[languages.en.menu.main]]
            identifier = "blog"
            name = "Blog"
            url = "https://blog.muxin.io/en"
            weight = -1
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About Me"
            url = "/about/"
