image: docker:stable

services:
  - docker:dind

variables:
  REPO: imxseraph/muxin-io
  NGINX: nginx

stages:
  - build 

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  tags: 
    - muxin-host
  script:
    - docker build -t $REPO:$NGINX .
    - docker push $REPO:$NGINX
