stages:
  - build
  - deploy 

build:
  stage: build
  image: docker:stable
  when: manual
  tags: 
    - muxin-host
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t imxseraph/muxin-io:nginx .
    - docker push imxseraph/muxin-io:nginx

deploy:
  stage: deploy
  image: centos:7
  when: manual
  tags:
    - muxin-host
  script:
    - yum install openssh-clients -y
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$AUTO_DEPLOY_KEY" > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - ssh-keyscan host.muxin.io > .ssh/known_hosts
    - chmod 644 .ssh/known_hosts
    - scp deploy.sh gitlab@host.muxin.io:~/
    - ssh gitlab@host.muxin.io "chmod +x deploy.sh && ./deploy.sh"
