stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  tags: 
    - muxin.io
  services:
    - docker:stable-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t imxseraph/muxin-io:gaia .
    - docker push imxseraph/muxin-io:gaia

deploy:
  stage: deploy
  image: imxseraph/muxin-io:ssh
  tags:
    - muxin.io
  script:
    - ssh -o StrictHostKeychecking=no root@muxin.in "cd /mnt/deploy/gaia && docker-compose down --rmi all && docker-compose up -d"
