stages:
  - build
  - deploy 

build:
  stage: build
  image: docker:stable
  tags: 
    - muxin-io
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t imxseraph/muxin-io:gaia .
    - docker push imxseraph/muxin-io:gaia

deploy:
  stage: deploy
  image: centos:7
  tags:
    - muxin-io
  script:
    - yum install openssh-clients -y
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan muxin.io > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh deploy@muxin.io "cd deploy/gaia && git pull && sudo docker-compose down --rmi all && sudo docker-compose up -d"
