image: docker:stable

services:
  - docker:dind

variables:
  REPO: imxseraph/muxin-io
  NGINX_TEST: nginx-test
  NGINX: nginx

stages:
  - test
  - release 

before_script:
  - echo -n "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME

test-nginx:
  stage: test
  tags: 
    - muxin-host
  script:
    - docker build -t $REPO:$NGINX_TEST nginx
    - docker push $REPO:$NGINX_TEST

release-nginx:
  stage: release
  tags: 
    - muxin-host
  when: manual
  script:
    - docker build -t $REPO:$NGINX nginx
    - docker push $REPO:$NGINX
