stages:
  - build
  - deploy 

build:
  stage: build
  image: docker:stable
  tags: 
    - muxin-io
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t imxseraph/muxin-io:nginx .
    - docker push imxseraph/muxin-io:nginx

deploy:
  stage: deploy
  image: centos:7
  tags:
    - muxin-io
  script:
    - yum install openssh-clients -y
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan host.muxin.io > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp deploy.sh deploy@host.muxin.io:~/
    - ssh deploy@host.muxin.io "chmod +x deploy.sh && ./deploy.sh && rm -f deploy.sh"
