image: docker:stable

services:
  - docker:dind

variables:
  REPO: imxseraph/muxin-io

stages:
  - build 

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  tags: 
    - muxin-host
  when: manual
  script:
    - docker build -t $REPO:latest .
    - docker push $REPO:latest
