name: Docker

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ${{ format('{0}{1}', 'docker.pkg.github.com/imxseraph/gaia/main:', github.sha) }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Log into registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME
  deploy:
    needs: push

    runs-on: ubuntu-latest
    steps:
      - name: Create the key
        run: echo '${{ secrets.PRIVATE_KEY }}' > key && chmod 600 key
      - name: Deploy
        run: ssh -i key -o StrictHostKeychecking=no root@muxin.io "cd /mnt/deploy/gaia && docker pull $IMAGE_NAME && docker-compose down && docker-compose up -d"
